package Hibernate.entidades;
// Generated 21/08/2015 05:39:10 PM by Hibernate Tools 3.6.0



/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private Integer idCuenta;
     private Compania compania;
     private String banco;
     private Integer convenio;
     private String transferencia;
     private String nombre;

    public Cuenta() {
    }

	
    public Cuenta(Compania compania) {
        this.compania = compania;
    }
    public Cuenta(Compania compania, String banco, Integer convenio, String transferencia, String nombre) {
       this.compania = compania;
       this.banco = banco;
       this.convenio = convenio;
       this.transferencia = transferencia;
       this.nombre = nombre;
    }
   
    public Integer getIdCuenta() {
        return this.idCuenta;
    }
    
    public void setIdCuenta(Integer idCuenta) {
        this.idCuenta = idCuenta;
    }
    public Compania getCompania() {
        return this.compania;
    }
    
    public void setCompania(Compania compania) {
        this.compania = compania;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }
    public Integer getConvenio() {
        return this.convenio;
    }
    
    public void setConvenio(Integer convenio) {
        this.convenio = convenio;
    }
    public String getTransferencia() {
        return this.transferencia;
    }
    
    public void setTransferencia(String transferencia) {
        this.transferencia = transferencia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


