package Hibernate.entidades;
// Generated 9/05/2016 11:25:54 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PagoReclamo generated by hbm2java
 */
public class PagoReclamo  implements java.io.Serializable {


     private Integer idPagoReclamo;
     private String tipoPago;
     private Date fechaPago;
     private String noTransferencia;
     private String cuentaBeneficiario;
     private Double cantidad;
     private String recibio;
     private String usuario;
     private String notas;
     private Set reclamos = new HashSet(0);

    public PagoReclamo() {
    }

    public PagoReclamo(String tipoPago, Date fechaPago, String noTransferencia, String cuentaBeneficiario, Double cantidad, String recibio, String usuario, String notas, Set reclamos) {
       this.tipoPago = tipoPago;
       this.fechaPago = fechaPago;
       this.noTransferencia = noTransferencia;
       this.cuentaBeneficiario = cuentaBeneficiario;
       this.cantidad = cantidad;
       this.recibio = recibio;
       this.usuario = usuario;
       this.notas = notas;
       this.reclamos = reclamos;
    }
   
    public Integer getIdPagoReclamo() {
        return this.idPagoReclamo;
    }
    
    public void setIdPagoReclamo(Integer idPagoReclamo) {
        this.idPagoReclamo = idPagoReclamo;
    }
    public String getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(String tipoPago) {
        this.tipoPago = tipoPago;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public String getNoTransferencia() {
        return this.noTransferencia;
    }
    
    public void setNoTransferencia(String noTransferencia) {
        this.noTransferencia = noTransferencia;
    }
    public String getCuentaBeneficiario() {
        return this.cuentaBeneficiario;
    }
    
    public void setCuentaBeneficiario(String cuentaBeneficiario) {
        this.cuentaBeneficiario = cuentaBeneficiario;
    }
    public Double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Double cantidad) {
        this.cantidad = cantidad;
    }
    public String getRecibio() {
        return this.recibio;
    }
    
    public void setRecibio(String recibio) {
        this.recibio = recibio;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getNotas() {
        return this.notas;
    }
    
    public void setNotas(String notas) {
        this.notas = notas;
    }
    public Set getReclamos() {
        return this.reclamos;
    }
    
    public void setReclamos(Set reclamos) {
        this.reclamos = reclamos;
    }



}


