package Hibernate.entidades;
// Generated 15/09/2015 10:35:58 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partida generated by hbm2java
 */
public class Partida  implements java.io.Serializable {


     private Integer idPartida;
     private Usuario usuario;
     private Proveedor proveedor;
     private Pedido pedido;
     private Orden ordenByIdOrden;
     private Orden ordenByEnlazada;
     private Catalogo catalogo;
     private Ejemplar ejemplar;
     private int idEvaluacion;
     private int subPartida;
     private boolean espHoj;
     private boolean espMec;
     private boolean espSus;
     private boolean espEle;
     private double dm;
     private double cam;
     private double repMin;
     private double repMed;
     private double repMax;
     private double pint;
     private double cant;
     private String med;
     private boolean refCoti;
     private boolean ori;
     private boolean nal;
     private boolean desm;
     private boolean pd;
     private double intDesm;
     private double intCamb;
     private double intRepMin;
     private double intRepMed;
     private double intRepMax;
     private double intPinMin;
     private double intPinMed;
     private double intPinMax;
     private String instruccion;
     private double CU;
     private double porcentaje;
     private double precioCiaSegurosCU;
     private double cantidadAut;
     private double precioAutCU;
     private int porcentajeUtilidad;
     private boolean autorizado;
     private double horas;
     private boolean refComp;
     private boolean so;
     private Date plazo;
     private String tipo;
     private boolean incluida;
     private boolean autorizadoValuacion;
     private Double pcp;
     private Double cantPcp;
     private String descripcionFactura;
     private Double precioFactura;
     private Double cantidadFactura;
     private Boolean facturado;
     private Integer facturaPedido;
     private boolean surtido;
     private boolean muestra;
     private boolean op;
     private Usuario mecanico;
     private Date fechaMecanico;
     private String oriCon;
     private double d;
     private double r;
     private double m;
     private Set partidaCotizacions = new HashSet(0);
     private Set movimientos = new HashSet(0);
     private Set perdidases = new HashSet(0);
     private Set pedidos = new HashSet(0);

    public Partida() {
    }

	
    public Partida(Orden ordenByIdOrden, int idEvaluacion, int subPartida, boolean espHoj, boolean espMec, boolean espSus, boolean espEle, double dm, double cam, double repMin, double repMed, double repMax, double pint, double cant, boolean refCoti, boolean ori, boolean nal, boolean desm, boolean pd, double intDesm, double intCamb, double intRepMin, double intRepMed, double intRepMax, double intPinMin, double intPinMed, double intPinMax, double CU, double porcentaje, double precioCiaSegurosCU, double cantidadAut, double precioAutCU, int porcentajeUtilidad, boolean autorizado, double horas, boolean refComp, boolean so, String tipo, boolean incluida, boolean autorizadoValuacion) {
        this.ordenByIdOrden = ordenByIdOrden;
        this.idEvaluacion = idEvaluacion;
        this.subPartida = subPartida;
        this.espHoj = espHoj;
        this.espMec = espMec;
        this.espSus = espSus;
        this.espEle = espEle;
        this.dm = dm;
        this.cam = cam;
        this.repMin = repMin;
        this.repMed = repMed;
        this.repMax = repMax;
        this.pint = pint;
        this.cant = cant;
        this.refCoti = refCoti;
        this.ori = ori;
        this.nal = nal;
        this.desm = desm;
        this.pd = pd;
        this.intDesm = intDesm;
        this.intCamb = intCamb;
        this.intRepMin = intRepMin;
        this.intRepMed = intRepMed;
        this.intRepMax = intRepMax;
        this.intPinMin = intPinMin;
        this.intPinMed = intPinMed;
        this.intPinMax = intPinMax;
        this.CU = CU;
        this.porcentaje = porcentaje;
        this.precioCiaSegurosCU = precioCiaSegurosCU;
        this.cantidadAut = cantidadAut;
        this.precioAutCU = precioAutCU;
        this.porcentajeUtilidad = porcentajeUtilidad;
        this.autorizado = autorizado;
        this.horas = horas;
        this.refComp = refComp;
        this.so = so;
        this.tipo = tipo;
        this.incluida = incluida;
        this.autorizadoValuacion = autorizadoValuacion;
    }
    public Partida(Usuario usuario, Proveedor proveedor, Pedido pedido, Orden ordenByIdOrden, Orden ordenByEnlazada, Catalogo catalogo, Ejemplar ejemplar, int idEvaluacion, int subPartida, boolean espHoj, boolean espMec, boolean espSus, boolean espEle, double dm, double cam, double repMin, double repMed, double repMax, double pint, double cant, String med, boolean refCoti, boolean ori, boolean nal, boolean desm, boolean pd, double intDesm, double intCamb, double intRepMin, double intRepMed, double intRepMax, double intPinMin, double intPinMed, double intPinMax, String instruccion, double CU, double porcentaje, double precioCiaSegurosCU, double cantidadAut, double precioAutCU, int porcentajeUtilidad, boolean autorizado, double horas, boolean refComp, boolean so, Date plazo, String tipo, boolean incluida, boolean autorizadoValuacion, Double pcp, Double cantPcp, String descripcionFactura, Double precioFactura, Double cantidadFactura, Boolean facturado, Integer facturaPedido, Boolean surtido, Boolean muestra, Boolean op, Usuario mecanico, Date fechaMecanico, String oriCon, double d, double r, double m, Set partidaCotizacions, Set movimientos, Set perdidases, Set pedidos) {
       this.usuario = usuario;
       this.proveedor = proveedor;
       this.pedido = pedido;
       this.ordenByIdOrden = ordenByIdOrden;
       this.ordenByEnlazada = ordenByEnlazada;
       this.catalogo = catalogo;
       this.ejemplar = ejemplar;
       this.idEvaluacion = idEvaluacion;
       this.subPartida = subPartida;
       this.espHoj = espHoj;
       this.espMec = espMec;
       this.espSus = espSus;
       this.espEle = espEle;
       this.dm = dm;
       this.cam = cam;
       this.repMin = repMin;
       this.repMed = repMed;
       this.repMax = repMax;
       this.pint = pint;
       this.cant = cant;
       this.med = med;
       this.refCoti = refCoti;
       this.ori = ori;
       this.nal = nal;
       this.desm = desm;
       this.pd = pd;
       this.intDesm = intDesm;
       this.intCamb = intCamb;
       this.intRepMin = intRepMin;
       this.intRepMed = intRepMed;
       this.intRepMax = intRepMax;
       this.intPinMin = intPinMin;
       this.intPinMed = intPinMed;
       this.intPinMax = intPinMax;
       this.instruccion = instruccion;
       this.CU = CU;
       this.porcentaje = porcentaje;
       this.precioCiaSegurosCU = precioCiaSegurosCU;
       this.cantidadAut = cantidadAut;
       this.precioAutCU = precioAutCU;
       this.porcentajeUtilidad = porcentajeUtilidad;
       this.autorizado = autorizado;
       this.horas = horas;
       this.refComp = refComp;
       this.so = so;
       this.plazo = plazo;
       this.tipo = tipo;
       this.incluida = incluida;
       this.autorizadoValuacion = autorizadoValuacion;
       this.pcp = pcp;
       this.cantPcp = cantPcp;
       this.descripcionFactura = descripcionFactura;
       this.precioFactura = precioFactura;
       this.cantidadFactura = cantidadFactura;
       this.facturado = facturado;
       this.facturaPedido = facturaPedido;
       this.partidaCotizacions = partidaCotizacions;
       this.movimientos = movimientos;
       this.perdidases = perdidases;
       this.pedidos = pedidos;
       this.surtido = surtido;
       this.muestra = muestra;
       this.op = op;
       this.mecanico= mecanico;
       this.fechaMecanico = fechaMecanico;
       this.oriCon = oriCon;
       this.d = d;
       this.r = r;
       this.m = m;
    }
   
    public Integer getIdPartida() {
        return this.idPartida;
    }
    
    public void setIdPartida(Integer idPartida) {
        this.idPartida = idPartida;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Orden getOrdenByIdOrden() {
        return this.ordenByIdOrden;
    }
    
    public void setOrdenByIdOrden(Orden ordenByIdOrden) {
        this.ordenByIdOrden = ordenByIdOrden;
    }
    public Orden getOrdenByEnlazada() {
        return this.ordenByEnlazada;
    }
    
    public void setOrdenByEnlazada(Orden ordenByEnlazada) {
        this.ordenByEnlazada = ordenByEnlazada;
    }
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }
    public Ejemplar getEjemplar() {
        return this.ejemplar;
    }
    
    public void setEjemplar(Ejemplar ejemplar) {
        this.ejemplar = ejemplar;
    }
    public int getIdEvaluacion() {
        return this.idEvaluacion;
    }
    
    public void setIdEvaluacion(int idEvaluacion) {
        this.idEvaluacion = idEvaluacion;
    }
    public int getSubPartida() {
        return this.subPartida;
    }
    
    public void setSubPartida(int subPartida) {
        this.subPartida = subPartida;
    }
    public boolean isEspHoj() {
        return this.espHoj;
    }
    
    public void setEspHoj(boolean espHoj) {
        this.espHoj = espHoj;
    }
    public boolean isEspMec() {
        return this.espMec;
    }
    
    public void setEspMec(boolean espMec) {
        this.espMec = espMec;
    }
    public boolean isEspSus() {
        return this.espSus;
    }
    
    public void setEspSus(boolean espSus) {
        this.espSus = espSus;
    }
    public boolean isEspEle() {
        return this.espEle;
    }
    
    public void setEspEle(boolean espEle) {
        this.espEle = espEle;
    }
    public double getDm() {
        return this.dm;
    }
    
    public void setDm(double dm) {
        this.dm = dm;
    }
    public double getCam() {
        return this.cam;
    }
    
    public void setCam(double cam) {
        this.cam = cam;
    }
    public double getRepMin() {
        return this.repMin;
    }
    
    public void setRepMin(double repMin) {
        this.repMin = repMin;
    }
    public double getRepMed() {
        return this.repMed;
    }
    
    public void setRepMed(double repMed) {
        this.repMed = repMed;
    }
    public double getRepMax() {
        return this.repMax;
    }
    
    public void setRepMax(double repMax) {
        this.repMax = repMax;
    }
    public double getPint() {
        return this.pint;
    }
    
    public void setPint(double pint) {
        this.pint = pint;
    }
    public double getCant() {
        return this.cant;
    }
    
    public void setCant(double cant) {
        this.cant = cant;
    }
    public String getMed() {
        return this.med;
    }
    
    public void setMed(String med) {
        this.med = med;
    }
    public boolean isRefCoti() {
        return this.refCoti;
    }
    
    public void setRefCoti(boolean refCoti) {
        this.refCoti = refCoti;
    }
    public boolean isOri() {
        return this.ori;
    }
    
    public void setOri(boolean ori) {
        this.ori = ori;
    }
    public boolean isNal() {
        return this.nal;
    }
    
    public void setNal(boolean nal) {
        this.nal = nal;
    }
    public boolean isDesm() {
        return this.desm;
    }
    
    public void setDesm(boolean desm) {
        this.desm = desm;
    }
    public boolean isPd() {
        return this.pd;
    }
    
    public void setPd(boolean pd) {
        this.pd = pd;
    }
    public double getIntDesm() {
        return this.intDesm;
    }
    
    public void setIntDesm(double intDesm) {
        this.intDesm = intDesm;
    }
    public double getIntCamb() {
        return this.intCamb;
    }
    
    public void setIntCamb(double intCamb) {
        this.intCamb = intCamb;
    }
    public double getIntRepMin() {
        return this.intRepMin;
    }
    
    public void setIntRepMin(double intRepMin) {
        this.intRepMin = intRepMin;
    }
    public double getIntRepMed() {
        return this.intRepMed;
    }
    
    public void setIntRepMed(double intRepMed) {
        this.intRepMed = intRepMed;
    }
    public double getIntRepMax() {
        return this.intRepMax;
    }
    
    public void setIntRepMax(double intRepMax) {
        this.intRepMax = intRepMax;
    }
    public double getIntPinMin() {
        return this.intPinMin;
    }
    
    public void setIntPinMin(double intPinMin) {
        this.intPinMin = intPinMin;
    }
    public double getIntPinMed() {
        return this.intPinMed;
    }
    
    public void setIntPinMed(double intPinMed) {
        this.intPinMed = intPinMed;
    }
    public double getIntPinMax() {
        return this.intPinMax;
    }
    
    public void setIntPinMax(double intPinMax) {
        this.intPinMax = intPinMax;
    }
    public String getInstruccion() {
        return this.instruccion;
    }
    
    public void setInstruccion(String instruccion) {
        this.instruccion = instruccion;
    }
    public double getCU() {
        return this.CU;
    }
    
    public void setCU(double CU) {
        this.CU = CU;
    }
    public double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(double porcentaje) {
        this.porcentaje = porcentaje;
    }
    public double getPrecioCiaSegurosCU() {
        return this.precioCiaSegurosCU;
    }
    
    public void setPrecioCiaSegurosCU(double precioCiaSegurosCU) {
        this.precioCiaSegurosCU = precioCiaSegurosCU;
    }
    public double getCantidadAut() {
        return this.cantidadAut;
    }
    
    public void setCantidadAut(double cantidadAut) {
        this.cantidadAut = cantidadAut;
    }
    public double getPrecioAutCU() {
        return this.precioAutCU;
    }
    
    public void setPrecioAutCU(double precioAutCU) {
        this.precioAutCU = precioAutCU;
    }
    public int getPorcentajeUtilidad() {
        return this.porcentajeUtilidad;
    }
    
    public void setPorcentajeUtilidad(int porcentajeUtilidad) {
        this.porcentajeUtilidad = porcentajeUtilidad;
    }
    public boolean isAutorizado() {
        return this.autorizado;
    }
    
    public void setAutorizado(boolean autorizado) {
        this.autorizado = autorizado;
    }
    public double getHoras() {
        return this.horas;
    }
    
    public void setHoras(double horas) {
        this.horas = horas;
    }
    public boolean isRefComp() {
        return this.refComp;
    }
    
    public void setRefComp(boolean refComp) {
        this.refComp = refComp;
    }
    public boolean isSo() {
        return this.so;
    }
    
    public void setSo(boolean so) {
        this.so = so;
    }
    public Date getPlazo() {
        return this.plazo;
    }
    
    public void setPlazo(Date plazo) {
        this.plazo = plazo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public boolean isIncluida() {
        return this.incluida;
    }
    
    public void setIncluida(boolean incluida) {
        this.incluida = incluida;
    }
    public boolean isAutorizadoValuacion() {
        return this.autorizadoValuacion;
    }
    
    public void setAutorizadoValuacion(boolean autorizadoValuacion) {
        this.autorizadoValuacion = autorizadoValuacion;
    }
    public Double getPcp() {
        return this.pcp;
    }
    
    public void setPcp(Double pcp) {
        this.pcp = pcp;
    }
    public Double getCantPcp() {
        return this.cantPcp;
    }
    
    public void setCantPcp(Double cantPcp) {
        this.cantPcp = cantPcp;
    }
    public String getDescripcionFactura() {
        return this.descripcionFactura;
    }
    
    public void setDescripcionFactura(String descripcionFactura) {
        this.descripcionFactura = descripcionFactura;
    }
    public Double getPrecioFactura() {
        return this.precioFactura;
    }
    
    public void setPrecioFactura(Double precioFactura) {
        this.precioFactura = precioFactura;
    }
    public Double getCantidadFactura() {
        return this.cantidadFactura;
    }
    
    public void setCantidadFactura(Double cantidadFactura) {
        this.cantidadFactura = cantidadFactura;
    }
    
    public Boolean getFacturado() {
        return this.facturado;
    }
    
    public void setFacturado(Boolean facturado) {
        this.facturado = facturado;
    }
    
    public Boolean getSurtido() {
        return this.surtido;
    }
    
    public void setSurtido(Boolean surtido) {
        this.surtido = surtido;
    }
    
    public Boolean getMuestra() {
        return this.muestra;
    }
    
    public void setMuestra(Boolean muestra) {
        this.muestra = muestra;
    }
    
    public Boolean getOp() {
        return this.op;
    }
    
    public void setMecanico(Usuario mecanico) {
        this.mecanico = mecanico;
    }
    
    public Usuario getMecanico() {
        return this.mecanico;
    }
    
    public void setFechaMecanico(Date fechaMecanico) {
        this.fechaMecanico = fechaMecanico;
    }
    
    public Date getFechaMecanico() {
        return this.fechaMecanico;
    }
    
    public void setOp(Boolean op) {
        this.op = op;
    }
    
    public Integer getFacturaPedido() {
        return this.facturaPedido;
    }
    
    public void setFacturaPedido(Integer facturaPedido) {
        this.facturaPedido = facturaPedido;
    }
    public Set getPartidaCotizacions() {
        return this.partidaCotizacions;
    }
    
    public void setPartidaCotizacions(Set partidaCotizacions) {
        this.partidaCotizacions = partidaCotizacions;
    }
    public Set getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }
    public Set getPerdidases() {
        return this.perdidases;
    }
    
    public void setPerdidases(Set perdidases) {
        this.perdidases = perdidases;
    }

    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }

    public String getOriCon() {
        return this.oriCon;
    }
    
    public void setOriCon(String oriCon) {
        this.oriCon = oriCon;
    }
    
    public double getD() {
        return this.d;
    }
    
    public void setD(double d) {
        this.d = d;
    }

    public double getR() {
        return this.r;
    }
    
    public void setR(double r) {
        this.r = r;
    }
    public double getM() {
        return this.m;
    }
    
    public void setM(double m) {
        this.m = m;
    }
}


