package Hibernate.entidades;
// Generated 9/05/2016 11:25:54 AM by Hibernate Tools 3.6.0



/**
 * XCobrar generated by hbm2java
 */
public class XCobrar  implements java.io.Serializable {


     private Integer idCobrar;
     private Reclamo reclamo;
     private int idPedido;

    public XCobrar() {
    }

    public XCobrar(Reclamo reclamo, int idPedido) {
       this.reclamo = reclamo;
       this.idPedido = idPedido;
    }
   
    public Integer getIdCobrar() {
        return this.idCobrar;
    }
    
    public void setIdCobrar(Integer idCobrar) {
        this.idCobrar = idCobrar;
    }
    public Reclamo getReclamo() {
        return this.reclamo;
    }
    
    public void setReclamo(Reclamo reclamo) {
        this.reclamo = reclamo;
    }
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }




}


