/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Integral;

import Hibernate.entidades.Usuario;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.filter.Filters;
import org.jdom2.input.SAXBuilder;
import org.jdom2.xpath.XPathExpression;
import org.jdom2.xpath.XPathFactory;

/**
 *
 * @author salvador
 */
public class respaldo extends javax.swing.JPanel {

    /**
     * Creates new form respaldo
     */
    File f;
    Herramientas h;
    private Usuario actor=null;
    private String sessionPrograma="";
    
    public respaldo(Usuario usr, String ses) {
        initComponents();
        actor=usr;
        sessionPrograma=ses;
        DescripcionFile();
    }

    
    private void DescripcionFile()
    {
        File backupFile = new File("respaldo/respaldo.sql");
        if(backupFile.exists()==true)
        {
            Long ms = backupFile.lastModified();
            Date d = new Date(ms);
            Calendar c = new GregorianCalendar();
            c.setTime(d);

            String dia = Integer.toString(c.get(Calendar.DATE));
            String mes = Integer.toString(c.get(Calendar.MONTH));
            String annio = Integer.toString(c.get(Calendar.YEAR));
            String hora = Integer.toString(c.get(Calendar.HOUR_OF_DAY));
            String minuto = Integer.toString(c.get(Calendar.MINUTE));
            String segundo = Integer.toString(c.get(Calendar.SECOND));
            String modificacion="Nombre del respaldo: respaldo.sql\n";
            modificacion+="Fecha de Modificación:"+dia+"/"+mes+"/"+annio+" "+hora+":"+minuto+":"+segundo+"\n";
            modificacion+="Tamaño:"+backupFile.length()+" bytes";
            ta_descripcion.setText(modificacion);
            if(ta_descripcion.getText().compareTo("")==0)
                b_guardar.setEnabled(false);
            else
                b_guardar.setEnabled(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aviso = new javax.swing.JFileChooser();
        jFrame1 = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t_texto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcion = new javax.swing.JTextArea();
        b_guardar = new javax.swing.JButton();

        aviso.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        aviso.setDialogTitle("Examinar");

        jFrame1.setAlwaysOnTop(true);
        jFrame1.setFocusable(false);
        jFrame1.setResizable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Creando el archivo de respaldo");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Espere un momento");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(19, 19, 19))))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(254, 254, 254));

        t_texto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t_texto.setText("Administración de la Base de Datos");

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Respaldar Base de Datos"));

        jLabel7.setText("Iniciar proceso de restauración");

        jButton4.setText("Respaldar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Nota: Cada vez que genera un respaldo el anterior es eliminado");

        jLabel10.setText("se recomienda guardar dicho archivo en algun dispositovo");

        jLabel11.setText("extraible.");

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 204), 1, true), "Detalles del archivo de respaldo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(51, 0, 204))); // NOI18N

        ta_descripcion.setEditable(false);
        ta_descripcion.setColumns(20);
        ta_descripcion.setRows(4);
        jScrollPane1.setViewportView(ta_descripcion);

        b_guardar.setText("Guardar");
        b_guardar.setEnabled(false);
        b_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b_guardar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(b_guardar))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel10)))
                                .addGap(0, 24, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(26, 26, 26))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_texto)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t_texto)
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        h=new Herramientas(actor, 0);
        h.session(sessionPrograma);
        if(actor.getRespaldar()==true)
        {
            try{
                Runtime runtime = Runtime.getRuntime();
                File folder = new File("respaldo/");
                folder.mkdirs();
                File backupFile = new File("respaldo/respaldo.sql");
                FileWriter fw = new FileWriter(backupFile);
                
                File f= new File("hibernate.cfg.xml");
                URL xmlFileURL =f.toURL();
                Document documentJDOM = new SAXBuilder().build(xmlFileURL);
                XPathExpression<Element> xPathExpression = XPathFactory.instance().compile("/hibernate-configuration/session-factory/property", Filters.element());
                List<Element> elementList = xPathExpression.evaluate(documentJDOM);
                //Esto es relativo a en que posición aparecen las lineas en el hibernate.cfg.xml
                String base=elementList.get(6).getText();
                String usuario=elementList.get(4).getText();
                String clave=elementList.get(5).getText();
                String servidor=elementList.get(7).getText();
                String puerto=elementList.get(8).getText();
                //System.out.println("mysqldump --opt --user="+usuario+" -password="+clave+" --host="+servidor+" "+base+" > r.sql");
                System.out.println("mysqldump --opt --user="+usuario+" --password="+clave+" --host="+servidor+" --port="+puerto+" "+base);
                Process child = runtime.exec("mysqldump --opt --user="+usuario+" --password="+clave+" --host="+servidor+" --port="+puerto+" "+base);
                
                InputStreamReader irs = new InputStreamReader(child.getInputStream());
                BufferedReader br = new BufferedReader(irs);

                String line;
                while( (line=br.readLine()) != null ) 
                {
                    fw.write(line + "\n");
                }
                fw.close();
                irs.close();
                br.close();
                DescripcionFile();
                JOptionPane.showMessageDialog(null, "Archivo generado correctamente.","Verificar",JOptionPane. INFORMATION_MESSAGE);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Error no se genero el archivo por el siguiente motivo:"+e.getMessage(), "Verificar",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Acceso denegado");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void b_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarActionPerformed
        // TODO add your handling code here:
        h=new Herramientas(actor, 0);
        h.session(sessionPrograma);
        if(actor.getRespaldar()==true)
        {
            FileNameExtensionFilter filtroImagen=new FileNameExtensionFilter("SQL","sql");
            aviso.setFileFilter(filtroImagen);
            int r=aviso.showSaveDialog(null);
            if(r==aviso.APPROVE_OPTION)
            {
                try 
                {
                    File a=aviso.getSelectedFile();
                    if(a.exists()==true)
                    {
                        int i=JOptionPane.showConfirmDialog(null, "Deseas remplazar el archivo?", "confirmación", JOptionPane.YES_NO_OPTION);
                        if(i==0)
                        {
                            File inFile = new File("respaldo/respaldo.sql");

                            FileInputStream in = new FileInputStream(inFile);
                            FileOutputStream out = new FileOutputStream(a);

                            int c;
                            while((c = in.read()) != -1)
                                out.write(c);

                            in.close();
                            out.close();
                            JOptionPane.showMessageDialog(null, "Archivo guardado!");
                        }
                    }
                    else
                    {
                        if(a.getName().indexOf(".sql")==-1)
                            a= new File(a.getAbsoluteFile()+".sql");
                        File inFile = new File("respaldo/respaldo.sql");
                        FileInputStream in = new FileInputStream(inFile);
                        FileOutputStream out = new FileOutputStream(a);
                        int c;
                        while((c = in.read()) != -1)
                            out.write(c);
                        in.close();
                        out.close();
                        JOptionPane.showMessageDialog(null, "Archivo guardado!");
                    }
                } catch (Exception e1) {
                    JOptionPane.showMessageDialog(null, "Error al guardar el archivo "+e1.getMessage());
                }
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Acceso denegado");
    }//GEN-LAST:event_b_guardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser aviso;
    private javax.swing.JButton b_guardar;
    private javax.swing.JButton jButton4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel t_texto;
    private javax.swing.JTextArea ta_descripcion;
    // End of variables declaration//GEN-END:variables
}
