/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Servicios;

import Hibernate.Util.HibernateUtil;
import Hibernate.entidades.Correo;
import Hibernate.entidades.Empleado;
import Hibernate.entidades.Usuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import org.hibernate.Session;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;
import Integral.DefaultTableHeaderCellRenderer;
import Integral.FormatoTabla;
import Integral.Herramientas;
import Integral.VerticalTableHeaderCellRenderer;

/**
 *
 * @author I.S.C Salvador
 */
public class bandejaSalida extends javax.swing.JPanel {

    Usuario usr;
    Herramientas h;
    String sessionPrograma;
    DefaultTableModel model;
    String[] columnas = new String [] {"Id","Destinatarios","CC","Asunto","Adjunto","Fecha"};
    FormatoTabla formato;
    /**
     * Creates new form bandejaSAlida
     */
    public bandejaSalida(Usuario usr, String ses) {
        initComponents();
        formato = new FormatoTabla();
        this.usr=usr;
        sessionPrograma=ses;
        cargaCorreo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_tabla = new javax.swing.JScrollPane();
        t_datos = new javax.swing.JTable();
        p_config = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        smtp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ttl = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        puerto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cuenta = new javax.swing.JTextField();
        clave = new javax.swing.JPasswordField();
        b_guardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        p_centro = new javax.swing.JPanel();

        t_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Destinatarios", "CC", "Asunto", "Adjunto", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t_datos.setRowHeight(19);
        t_datos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        t_datos.getTableHeader().setReorderingAllowed(false);
        p_tabla.setViewportView(t_datos);

        p_config.setBackground(new java.awt.Color(254, 254, 254));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Configuracion de correo Electronico");

        jLabel3.setText("SMTP:");

        jLabel4.setText("TTL:");

        ttl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activado", "Desactivado" }));

        jLabel5.setText("Puerto:");

        jLabel6.setText("Cuenta:");

        jLabel7.setText("Contraseña:");

        b_guardar.setBackground(new java.awt.Color(90, 66, 126));
        b_guardar.setForeground(new java.awt.Color(254, 254, 254));
        b_guardar.setIcon(new ImageIcon("imagenes/guardar.png"));
        b_guardar.setText("Actualizar");
        b_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_configLayout = new javax.swing.GroupLayout(p_config);
        p_config.setLayout(p_configLayout);
        p_configLayout.setHorizontalGroup(
            p_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_configLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(p_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(p_configLayout.createSequentialGroup()
                            .addGroup(p_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(16, 16, 16)
                            .addGroup(p_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(smtp, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(p_configLayout.createSequentialGroup()
                                    .addComponent(ttl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(puerto))))
                        .addGroup(p_configLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cuenta))
                        .addGroup(p_configLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_guardar)))
                    .addComponent(jLabel2))
                .addGap(296, 296, 296))
        );
        p_configLayout.setVerticalGroup(
            p_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_configLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(p_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(smtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ttl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(2, 135, 242));
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setIcon(new ImageIcon("imagenes/boton_agregar.png"));
        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new ImageIcon("imagenes/sobre.png"));

        jButton3.setBackground(new java.awt.Color(2, 135, 242));
        jButton3.setForeground(new java.awt.Color(254, 254, 254));
        jButton3.setIcon(new ImageIcon("imagenes/reenviar.png"));
        jButton3.setText("Reembiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(2, 135, 242));
        jButton4.setForeground(new java.awt.Color(254, 254, 254));
        jButton4.setIcon(new ImageIcon("imagenes/borra.png"));
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(873, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(2, 135, 242));
        jButton2.setForeground(new java.awt.Color(254, 254, 254));
        jButton2.setIcon(new ImageIcon("imagenes/sen.png"));
        jButton2.setText("Enviados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(2, 135, 242));
        jButton5.setForeground(new java.awt.Color(254, 254, 254));
        jButton5.setIcon(new ImageIcon("imagenes/contacto.png"));
        jButton5.setText("Config.");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(354, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.LINE_START);

        p_centro.setBackground(new java.awt.Color(254, 254, 254));
        p_centro.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Bandeja de Salida", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 1, 12))); // NOI18N
        p_centro.setLayout(new java.awt.BorderLayout());
        add(p_centro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EnviarCorreo en= new EnviarCorreo(new javax.swing.JFrame(), true, "","", "", null, this.usr, this.sessionPrograma);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        en.setLocation((d.width/2)-(en.getWidth()/2), (d.height/2)-(en.getHeight()/2));
        en.setVisible(true);
        cargaCorreo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        p_centro.removeAll();
        p_centro.add(this.p_tabla);
        p_centro.updateUI();
        cargaCorreo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        h=new Herramientas(usr, 0);
        h.session(sessionPrograma);
        if(t_datos.getSelectedRow()>-1)
        {
            Session session = HibernateUtil.getSessionFactory().openSession();
            try
            {
                session.beginTransaction().begin();
                usr=(Usuario)session.get(Usuario.class, usr.getIdUsuario());
                Correo m=(Correo)session.get(Correo.class, Integer.parseInt(t_datos.getValueAt(t_datos.getSelectedRow(), 0).toString()));
                usr.eliminaCorreo(m);
                session.update(usr);
                session.delete(m);
                if(m.getIdCorreo()!=null)
                {
                    File archivo=new File("adjuntos/"+m.getIdCorreo()+"/"+m.getArchivo());
                    archivo.delete();
                    archivo=new File("adjuntos/"+m.getIdCorreo());
                    archivo.delete();
                }
                session.getTransaction().commit();
                JOptionPane.showMessageDialog(null, "¡Correo eliminado!");
                this.cargaCorreo();
            }catch(Exception e )
            {
                session.getTransaction().rollback();
                JOptionPane.showMessageDialog(null, "¡Error al eliminar el correo[!"+e+"]");
            }
            if(session!=null)
                if(session.isOpen())
                    session.close();
        }
        else
          JOptionPane.showMessageDialog(null, "¡Debe seleccionar un correo primero!");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        EnviarCorreo en;
        h=new Herramientas(usr, 0);
        h.session(sessionPrograma);
        if(t_datos.getSelectedRow()>-1)
        {
            Session session = HibernateUtil.getSessionFactory().openSession();
            try
            {
                Correo m=(Correo)session.get(Correo.class, Integer.parseInt(t_datos.getValueAt(t_datos.getSelectedRow(), 0).toString()));
                if(m.getArchivo()==null)
                    en= new EnviarCorreo(
                            new javax.swing.JFrame(), 
                            true, 
                            m.getDestinatario(), 
                            m.getAsunto(), 
                            m.getMensaje(), 
                            null, 
                            this.usr, 
                            this.sessionPrograma);
                else
                {
                    en= new EnviarCorreo(
                            new javax.swing.JFrame(), 
                            true, 
                            m.getDestinatario(), 
                            m.getAsunto(), 
                            m.getMensaje(), 
                            new File("adjuntos/"+m.getIdCorreo()+"/"+m.getArchivo()), 
                            this.usr, 
                            this.sessionPrograma);
                }
                Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
                en.setLocation((d.width/2)-(en.getWidth()/2), (d.height/2)-(en.getHeight()/2));
                en.setVisible(true);
                cargaCorreo();
            }catch(Exception e)
            {
                System.out.println(e);
            }
            if(session!=null)
                if(session.isOpen())
                    session.close();
        }
        else
          JOptionPane.showMessageDialog(null, "¡Debe seleccionar un correo primero!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        h=new Herramientas(usr, 0);
        h.session(sessionPrograma);
        Session session = HibernateUtil.getSessionFactory().openSession();
        try
        {
            session.beginTransaction().begin();
            usr=(Usuario)session.get(Usuario.class, usr.getIdUsuario());
            if(usr.getEmpleado().getSmtp()!=null)
                smtp.setText(usr.getEmpleado().getSmtp());
            else
                smtp.setText("");
            if(usr.getEmpleado().getAutentificacion()!=null)
            {
                if(usr.getEmpleado().getAutentificacion()==true)
                {
                    ttl.setSelectedItem("Activado");
                }
                else
                    ttl.setSelectedItem("Desactivado");
            }
            else
                ttl.setSelectedItem("Desactivado");
                
            if(usr.getEmpleado().getPuerto()!=null)
                puerto.setText(""+usr.getEmpleado().getPuerto());
            else
                puerto.setText("");
            if(usr.getEmpleado().getEmail()!=null)
                cuenta.setText(usr.getEmpleado().getEmail());
            else
                cuenta.setText("");
            if(usr.getEmpleado().getPassword()!=null)
                clave.setText(usr.getEmpleado().getPassword());
            else
                clave.setText(usr.getEmpleado().getPassword());
        }
        catch(Exception e )
        {
            session.getTransaction().rollback();
            JOptionPane.showMessageDialog(null, "¡Error[!"+e+"]");
        }
        if(session!=null)
            if(session.isOpen())
                session.close();
        p_centro.removeAll();
        p_centro.add(this.p_config);
        p_centro.updateUI();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void b_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarActionPerformed
        // TODO add your handling code here:
        h=new Herramientas(usr, 0);
        h.session(sessionPrograma);
        Session session = HibernateUtil.getSessionFactory().openSession();
        try
        {
            session.beginTransaction().begin();
            usr=(Usuario)session.get(Usuario.class, usr.getIdUsuario());
            Empleado em=usr.getEmpleado();
            
            if(smtp.getText().compareTo("")==0)
                em.setSmtp(null);
            else
                em.setSmtp(smtp.getText());
            
            if(ttl.getSelectedItem().toString().compareTo("Activado")==0)
            {
                em.setAutentificacion(true);
                em.setTls(true);
            }
            else
            {
                em.setAutentificacion(false);
                em.setTls(false);
            }
                
            if(puerto.getText().toString().compareTo("")==0)
                em.setPuerto(null);
            else
                em.setPuerto(Integer.parseInt(puerto.getText().toString()));
            
            if(cuenta.getText().compareTo("")==0)
                em.setEmail(null);
            else
                em.setEmail(cuenta.getText());
            
            if(clave.getPassword()==null)
                em.setPassword(null);
            else
                em.setPassword(clave.getText());
            session.update(em);
            session.beginTransaction().commit();
            JOptionPane.showMessageDialog(null, "Datos Almacenados");
        }
        catch(Exception e )
        {
            session.getTransaction().rollback();
            JOptionPane.showMessageDialog(null, "¡Error[!"+e+"]");
        }
        if(session!=null)
            if(session.isOpen())
                session.close();
    }//GEN-LAST:event_b_guardarActionPerformed

    
    DefaultTableModel ModeloTablaReporte(int renglones, String columnas[])
        {
            model = new DefaultTableModel(new Object [renglones][12], columnas)
            {
                Class[] types = new Class [] {
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    javax.swing.JLabel.class,
                    java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
                };

                public void setValueAt(Object value, int row, int col)
                 {
                     Vector vector = (Vector)this.dataVector.elementAt(row);
                     Object celda = ((Vector)this.dataVector.elementAt(row)).elementAt(col);
                     switch(col)
                     {
                         case 0:
                             vector.setElementAt(value, col);
                             this.dataVector.setElementAt(vector, row);
                             fireTableCellUpdated(row, col);
                             //calcula_totales();
                             break;

                         case 4:
                             vector.setElementAt(value, col);
                             this.dataVector.setElementAt(vector, row);
                             fireTableCellUpdated(row, col);
                             //calcula_totales();
                             break;
                         
                         default:
                             vector.setElementAt(value, col);
                             this.dataVector.setElementAt(vector, row);
                             fireTableCellUpdated(row, col);
                             break;
                     }
                 }
                
                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            };
            return model;
        }
    
    public void cargaCorreo()
    {
        Correo[] mails;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try
        {
            session.beginTransaction().begin();
            mails = (Correo[]) session.createCriteria(Correo.class).add(Restrictions.eq("usuario.idUsuario", usr.getIdUsuario())).addOrder(Order.desc("fecha")).list().toArray(new Correo[0]);
            t_datos.setModel(ModeloTablaReporte(mails.length, columnas));
            JLabel b=new JLabel("");
            b.setIcon(new ImageIcon("imagenes/adjunto1.png"));
            b.setVisible(true);
            for(int r=0; r<mails.length; r++)
            {
                t_datos.setValueAt(""+mails[r].getIdCorreo(), r, 0);
                t_datos.setValueAt(mails[r].getDestinatario(), r, 1);
                t_datos.setValueAt(mails[r].getCc(), r, 2);
                t_datos.setValueAt(mails[r].getAsunto(), r, 3);    
                if(mails[r].getArchivo()!=null)
                {
                    b.setText(mails[r].getArchivo());
                    t_datos.setValueAt(b, r, 4);
                }
                else
                    t_datos.setValueAt("", r, 4);
                t_datos.setValueAt(mails[r].getFecha(), r, 5);
            }
            if(session.isOpen())
                session.close();
            formatoTabla();
        }catch(Exception e)
        {
            System.out.println(e);
        }
        if(session!=null)
            if(session.isOpen())
                session.close();
    }

    
       public void tabla_tamaños()
   {
        TableColumnModel col_model = t_datos.getColumnModel();
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);
        JLabel b=new JLabel("");

        for (int i=0; i<t_datos.getColumnCount(); i++)
        {
  	      TableColumn column = col_model.getColumn(i);
              switch(i)
              {
                  case 0://N°
                      column.setPreferredWidth(40);
                      break;
                  case 1://#
                      column.setPreferredWidth(150);
                      break;
                  case 2://Grupo
                      column.setPreferredWidth(150);
                      break;
                  case 3://descripcion
                      column.setPreferredWidth(250);
                      break;
                  case 4://D/M
                      column.setPreferredWidth(20);
                      break;
                  case 5://rep min
                      column.setPreferredWidth(80);
                      break;
                      
                  default:
                      column.setPreferredWidth(100);
                      break;
              }
        }
        JTableHeader header = t_datos.getTableHeader();
        header.setBackground(new java.awt.Color(90,66,126));//102,102,102
        header.setForeground(Color.white);
   }  
       
   public void formatoTabla()
   {
        TableCellRenderer textNormal = new DefaultTableHeaderCellRenderer();        
        TableCellRenderer headerRenderer = new VerticalTableHeaderCellRenderer();
        Enumeration columns = t_datos.getColumnModel().getColumns();
        
        for(int x=0; x<t_datos.getColumnModel().getColumnCount(); x++)
        {
            t_datos.getColumnModel().getColumn(x).setHeaderRenderer(textNormal);
        } 
        tabla_tamaños();
        t_datos.setShowVerticalLines(true);
        t_datos.setShowHorizontalLines(true);
        
        t_datos.setDefaultRenderer(JLabel.class, formato); 
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_guardar;
    private javax.swing.JPasswordField clave;
    private javax.swing.JTextField cuenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel p_centro;
    private javax.swing.JPanel p_config;
    private javax.swing.JScrollPane p_tabla;
    private javax.swing.JTextField puerto;
    private javax.swing.JTextField smtp;
    private javax.swing.JTable t_datos;
    private javax.swing.JComboBox ttl;
    // End of variables declaration//GEN-END:variables
}
