/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Servicios;

import Hibernate.Util.HibernateUtil;
import Hibernate.entidades.Correo;
import Hibernate.entidades.Usuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import Integral.Herramientas;

/**
 *
 * @author I.S.C Salvador
 */
public class EnviarCorreo extends javax.swing.JDialog {

    File archivo=null;
    Herramientas h;
    Usuario usr;
    String sessionPrograma="";
    /**
     * Creates new form EnviarCorreo
     */
    public EnviarCorreo(java.awt.Frame parent, boolean modal, String correo, String asunto, String msg, File arch, Usuario usuario, String ses) 
    {
        initComponents();
        usr=usuario;
        sessionPrograma=ses;
    
        t_asunto.setText(asunto);
        t_from.setText(correo);
        t_mensaje.setText(msg);
        if(arch!=null)
        {
            archivo=arch;
            t_archivo.setText(archivo.getName());
            try{
                JFileChooser jf=new JFileChooser();
                jf.setSelectedFile(archivo);
                t_archivo.setIcon(jf.getIcon(arch));
            //sun.awt.shell.ShellFolder sf = sun.awt.shell.ShellFolder.getShellFolder(archivo);
            //mt_archivo.setIcon(new ImageIcon(sf.getIcon(true)));
            }catch(Exception e){System.out.println(e);}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        t_archivo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        b_enviar = new javax.swing.JButton();
        b_enviar.setContentAreaFilled(false);
        b_adjuntar = new javax.swing.JButton();
        b_adjuntar.setContentAreaFilled(false);
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_mensaje = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        t_from = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_cc = new javax.swing.JTextField();
        add1 = new javax.swing.JButton();
        add2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        t_asunto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enviar correo");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jPanel4.setBackground(new java.awt.Color(2, 135, 242));

        t_archivo.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        t_archivo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t_archivo)
                .addContainerGap(539, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t_archivo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_enviar.setIcon(new ImageIcon("imagenes/send.png"));
        b_enviar.setText("Enviar");
        b_enviar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        b_enviar.setPressedIcon(new ImageIcon("imagenes/send2.png"));
        b_enviar.setRolloverIcon(new ImageIcon("imagenes/send1.png"));
        b_enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b_enviarMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_enviarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_enviarMouseEntered(evt);
            }
        });
        b_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_enviarActionPerformed(evt);
            }
        });
        jPanel1.add(b_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        b_adjuntar.setIcon(new ImageIcon("imagenes/adjunto.png"));
        b_adjuntar.setText("Adjuntar");
        b_adjuntar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        b_adjuntar.setPressedIcon(new ImageIcon("imagenes/adjunto2.png"));
        b_adjuntar.setRolloverIcon(new ImageIcon("imagenes/adjunto1.png"));
        b_adjuntar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b_adjuntarMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_adjuntarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_adjuntarMouseEntered(evt);
            }
        });
        b_adjuntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_adjuntarActionPerformed(evt);
            }
        });
        jPanel1.add(b_adjuntar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jLabel1.setIcon(new ImageIcon("imagenes/procesos1.png"));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 71));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Contenido del Mensaje", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP));

        t_mensaje.setBackground(new java.awt.Color(204, 255, 255));
        t_mensaje.setColumns(20);
        t_mensaje.setRows(5);
        jScrollPane1.setViewportView(t_mensaje);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Para:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("CC:");

        add1.setBackground(new java.awt.Color(2, 135, 242));
        add1.setIcon(new ImageIcon("imagenes/contacto.png"));
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });

        add2.setBackground(new java.awt.Color(2, 135, 242));
        add2.setIcon(new ImageIcon("imagenes/contacto.png"));
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Asunto:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_asunto, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(24, 24, 24))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(16, 16, 16)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(t_from, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                                    .addComponent(t_cc))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(t_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(t_cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_asunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_adjuntarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_adjuntarMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_b_adjuntarMouseReleased

    private void b_adjuntarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_adjuntarMouseEntered
        // TODO add your handling code here:
        b_adjuntar.setForeground(Color.blue);
    }//GEN-LAST:event_b_adjuntarMouseEntered

    private void b_adjuntarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_adjuntarMouseExited
        // TODO add your handling code here:
        b_adjuntar.setForeground(Color.black);
    }//GEN-LAST:event_b_adjuntarMouseExited

    private void b_enviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_enviarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_b_enviarMouseEntered

    private void b_enviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_enviarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_b_enviarMouseExited

    private void b_enviarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_enviarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_b_enviarMouseReleased

    private void b_adjuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_adjuntarActionPerformed
        // TODO add your handling code here:
        //h=new Herramientas(usr, 0);
        //h.session(sessionPrograma);
        
        JFileChooser selector=new JFileChooser();
        //selector.setFileFilter(new ExtensionFileFilter("JPG and JPEG", new String[] { "JPG", "JPEG" }));
        int estado=1;
        File destino=null;
        estado=selector.showOpenDialog(null);
        if(estado==0)
        {
            try{
            archivo=null;
            archivo=selector.getSelectedFile();
            t_archivo.setText(archivo.getName());
            JFileChooser jf=new JFileChooser();
            jf.setSelectedFile(archivo);
            t_archivo.setIcon(jf.getFileSystemView().getSystemIcon(archivo));
            //sun.awt.shell.ShellFolder sf = sun.awt.shell.ShellFolder.getShellFolder(archivo);
            //t_archivo.setIcon(new ImageIcon(sf.getIcon(true)));
            }catch(Exception e){}
        }
        else
        {
            archivo=null;
            t_archivo.setText("");
            t_archivo.setIcon(null);
        }
    }//GEN-LAST:event_b_adjuntarActionPerformed

    private void b_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_enviarActionPerformed
        // TODO add your handling code here:
        if(t_from.getText().compareTo("")!=0)
        {
            h=new Herramientas(usr, 0);
            h.session(sessionPrograma);
        
            
            Session sesql = HibernateUtil.getSessionFactory().openSession();
            String smtp="";
            boolean ttl=false;
            String puerto="";
            String envia="";
            String clave="";
            try
            {
                usr=(Usuario)sesql.get(Usuario.class, usr.getIdUsuario());
                if(usr.getEmpleado().getSmtp()!=null)
                    smtp=usr.getEmpleado().getSmtp();
                
                if(usr.getEmpleado().getAutentificacion()!=null)
                {
                    if(usr.getEmpleado().getAutentificacion()==true)
                    ttl=true;
                }
                
                if(usr.getEmpleado().getPuerto()!=null)
                    puerto=""+usr.getEmpleado().getPuerto();
                
                if(usr.getEmpleado().getEmail()!=null)
                    envia=""+usr.getEmpleado().getEmail();//salvadoranaya@tractoservicio.com";
                
                if(usr.getEmpleado().getPassword()!=null)
                    clave=usr.getEmpleado().getPassword();
                
              // se obtiene el objeto Session.
                Properties props = new Properties();
                props.put("mail.smtp.host", smtp);
                props.setProperty("mail.smtp.starttls.enable", ""+ttl);
                props.setProperty("mail.smtp.port", puerto);
                props.setProperty("mail.smtp.user", envia);
                props.setProperty("mail.smtp.auth", "true");

                javax.mail.Session session = javax.mail.Session.getDefaultInstance(props, null);
                // session.setDebug(true);

                // Se compone la parte del texto
                BodyPart texto = new MimeBodyPart();
                texto.setText(t_mensaje.getText());

                // Una MultiParte para agrupar texto e imagen.
                MimeMultipart multiParte = new MimeMultipart();
                multiParte.addBodyPart(texto);
                
                String nom="";
                if(archivo!=null)
                {
                    if(archivo.exists())
                    {
                        // Se compone el adjunto con la imagen
                        BodyPart adjunto = new MimeBodyPart();
                        adjunto.setDataHandler(
                            new DataHandler(new FileDataSource(archivo.getAbsolutePath())));
                        adjunto.setFileName(archivo.getName());
                        nom=archivo.getName();
                        multiParte.addBodyPart(adjunto);
                    }
                }

                // Se compone el correo, dando to, from, subject y el
                // contenido.
                MimeMessage message = new MimeMessage(session);
                message.setFrom(new InternetAddress(envia));
                
                String [] direcciones=t_from.getText().split(";");
                for(int x=0; x<direcciones.length; x++)
                {
                    if(direcciones[x].compareTo("")!=0)
                        message.addRecipient(Message.RecipientType.TO, new InternetAddress(direcciones[x].replace(" ","")));
                }
                
                String [] dirCC=t_cc.getText().split(";");
                for(int y=0; y<dirCC.length; y++)
                {
                    if(dirCC[y].compareTo("")!=0)
                        message.addRecipient(Message.RecipientType.CC, new InternetAddress(dirCC[y].replace(" ","")));
                }
                    
                message.setSubject(t_asunto.getText());
                message.setContent(multiParte);

                // Se envia el correo.
                sesql.beginTransaction().begin();
                
                Date fechaMail = new Date();
                        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
                        String valor=dateFormat.format(fechaMail);
                        String [] fecha = valor.split("-");
                        String [] hora=fecha[2].split(":");
                        String [] aux=hora[0].split(" ");
                        fecha[2]=aux[0];
                        hora[0]=aux[1];
                        Calendar calendario = Calendar.getInstance();
                        calendario.set(
                        Integer.parseInt(fecha[2]), 
                        Integer.parseInt(fecha[1])-1, 
                        Integer.parseInt(fecha[0]), 
                        Integer.parseInt(hora[0]), 
                        Integer.parseInt(hora[1]), 
                        Integer.parseInt(hora[2]));
                        
                if(t_asunto.getText().compareTo("")==0)
                {
                    int opt=JOptionPane.showConfirmDialog(this, "Confirma que deseas enviar correo sin asunto");
                    if(opt==0)
                    {
                        usr = (Usuario)sesql.get(Usuario.class, usr.getIdUsuario());
                        
                        Correo cor;
                        if(nom.compareTo("")==0)
                            cor=new Correo(this.usr, t_from.getText(), t_cc.getText(), t_asunto.getText(), t_mensaje.getText(), null, calendario.getTime());
                        else
                            cor=new Correo(this.usr, t_from.getText(), t_cc.getText(), t_asunto.getText(), t_mensaje.getText(), nom, calendario.getTime());
                        int num=(int)sesql.save(cor);
                        Transport t = session.getTransport("smtp");
                        t.connect(envia, clave);
                        t.sendMessage(message, message.getAllRecipients());
                        t.close();
                        if(nom.compareTo("")!=0)
                        {
                            File folder = new File("ordenes/"+"/archivos");
                            folder.mkdirs();
                            File destino = new File("adjuntos/"+num+"/");
                            destino.mkdirs();
                            destino = new File("adjuntos/"+num+"/"+archivo.getName());
                            InputStream in = new FileInputStream(archivo);
                            OutputStream out = new FileOutputStream(destino);
                            byte[] buf = new byte[1024];
                            int len;
                            while ((len = in.read(buf)) > 0) 
                            {
                                out.write(buf, 0, len);
                            }
                            in.close();
                            out.close();
                        }
                        sesql.beginTransaction().commit();
                        JOptionPane.showMessageDialog(null, "El correo fue enviado");
                        this.dispose();
                    }
                }
                else
                {
                    Correo cor;
                    if(nom.compareTo("")==0)
                    {
                        cor=new Correo(this.usr, t_from.getText(), t_cc.getText(), t_asunto.getText(), t_mensaje.getText(), null, calendario.getTime());
                    }
                    else
                    {
                        cor=new Correo(this.usr, t_from.getText(), t_cc.getText(), t_asunto.getText(), t_mensaje.getText(), nom, calendario.getTime());
                    }
                    int num=(int)sesql.save(cor);
                    Transport t = session.getTransport("smtp");
                    t.connect(envia, clave);
                    t.sendMessage(message, message.getAllRecipients());
                    t.close();
                    if(nom.compareTo("")!=0)
                    {
                        File folder = new File("ordenes/"+"/archivos");
                        folder.mkdirs();
                        File destino = new File("adjuntos/"+num+"/");
                        destino.mkdirs();
                        destino = new File("adjuntos/"+num+"/"+archivo.getName());
                        InputStream in = new FileInputStream(archivo);
                        OutputStream out = new FileOutputStream(destino);
                        byte[] buf = new byte[1024];
                        int len;
                        while ((len = in.read(buf)) > 0) 
                        {
                            out.write(buf, 0, len);
                        }
                        in.close();
                        out.close();
                    }
                    //sesql.beginTransaction().begin();
                    
                    sesql.beginTransaction().commit();
                    JOptionPane.showMessageDialog(null, "El correo fue enviado");
                    this.dispose();
                }
            }
            catch (Exception e)
            {
                //e.printStackTrace();
                sesql.beginTransaction().rollback();
                JOptionPane.showMessageDialog(null, "error al enviar el correo:"+e);
            }
            if(sesql!=null)
                if(sesql.isOpen())
                    sesql.close();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "¡Debes ingresar un destinatario!");
            t_from.requestFocus();
        }
    }//GEN-LAST:event_b_enviarActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        // TODO add your handling code here:
        direcciones obj = new direcciones(new javax.swing.JFrame(), true);
        obj.t_busca.requestFocus();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        obj.setLocation((d.width/2)-(obj.getWidth()/2), (d.height/2)-(obj.getHeight()/2));
        obj.setVisible(true);

        String dir=obj.getReturnStatus();
        if (dir!=null)
        {
            if(t_from.getText().compareTo("")!=0)
                t_from.setText(t_from.getText()+";"+dir);
            else
                t_from.setText(dir);
        }
    }//GEN-LAST:event_add1ActionPerformed

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
        // TODO add your handling code here:
        direcciones obj = new direcciones(new javax.swing.JFrame(), true);
        obj.t_busca.requestFocus();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        obj.setLocation((d.width/2)-(obj.getWidth()/2), (d.height/2)-(obj.getHeight()/2));
        obj.setVisible(true);

        String dir=obj.getReturnStatus();
        if (dir!=null)
        {
            if(t_cc.getText().compareTo("")!=0)
                t_cc.setText(t_cc.getText()+";"+dir);
            else
                t_cc.setText(dir);
        }
    }//GEN-LAST:event_add2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add1;
    private javax.swing.JButton add2;
    private javax.swing.JButton b_adjuntar;
    private javax.swing.JButton b_enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel t_archivo;
    private javax.swing.JTextField t_asunto;
    private javax.swing.JTextField t_cc;
    private javax.swing.JTextField t_from;
    private javax.swing.JTextArea t_mensaje;
    // End of variables declaration//GEN-END:variables
}
